// GENERATED by Background/scripts/generate_ui.py; do not edit.
#pragma once
#include <cmath>
#include <stdexcept>
#include <string>
namespace sbg {
struct Params {
    int method = 0;
    int output = 0;
    double key_r = 0;
    double key_g = 1;
    double key_b = 0;
    double tolerance = 0.13;
    double transition = 0.08;
    double despill = 0.65;
    double feather = 1.2;
    double edge_shift = 0;
    double refine = 0.5;
    double blur = 24;
    double fill_r = 0.12;
    double fill_g = 0.12;
    double fill_b = 0.14;
    void validate() const {
        if (!std::isfinite(double(method)) || method < 0 || method > 1) throw std::invalid_argument("Invalid method");
        if (!std::isfinite(double(output)) || output < 0 || output > 2) throw std::invalid_argument("Invalid output");
        if (!std::isfinite(double(key_r)) || key_r < 0 || key_r > 1) throw std::invalid_argument("Invalid key_r");
        if (!std::isfinite(double(key_g)) || key_g < 0 || key_g > 1) throw std::invalid_argument("Invalid key_g");
        if (!std::isfinite(double(key_b)) || key_b < 0 || key_b > 1) throw std::invalid_argument("Invalid key_b");
        if (!std::isfinite(double(tolerance)) || tolerance < 0.005 || tolerance > 0.6) throw std::invalid_argument("Invalid tolerance");
        if (!std::isfinite(double(transition)) || transition < 0.005 || transition > 0.3) throw std::invalid_argument("Invalid transition");
        if (!std::isfinite(double(despill)) || despill < 0 || despill > 1) throw std::invalid_argument("Invalid despill");
        if (!std::isfinite(double(feather)) || feather < 0 || feather > 12) throw std::invalid_argument("Invalid feather");
        if (!std::isfinite(double(edge_shift)) || edge_shift < -8 || edge_shift > 8) throw std::invalid_argument("Invalid edge_shift");
        if (!std::isfinite(double(refine)) || refine < 0 || refine > 1) throw std::invalid_argument("Invalid refine");
        if (!std::isfinite(double(blur)) || blur < 0 || blur > 80) throw std::invalid_argument("Invalid blur");
        if (!std::isfinite(double(fill_r)) || fill_r < 0 || fill_r > 1) throw std::invalid_argument("Invalid fill_r");
        if (!std::isfinite(double(fill_g)) || fill_g < 0 || fill_g > 1) throw std::invalid_argument("Invalid fill_g");
        if (!std::isfinite(double(fill_b)) || fill_b < 0 || fill_b > 1) throw std::invalid_argument("Invalid fill_b");
    }
    void set(const std::string& key, double value) {
        if (!std::isfinite(value)) throw std::invalid_argument("Non-finite parameter");
        if (key == "method") { if(value < 0 || value > 1 || std::floor(value) != value) throw std::invalid_argument("Invalid method"); method=static_cast<int>(value); return; }
        if (key == "output") { if(value < 0 || value > 2 || std::floor(value) != value) throw std::invalid_argument("Invalid output"); output=static_cast<int>(value); return; }
        if (key == "key_r") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid key_r"); key_r=static_cast<double>(value); return; }
        if (key == "key_g") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid key_g"); key_g=static_cast<double>(value); return; }
        if (key == "key_b") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid key_b"); key_b=static_cast<double>(value); return; }
        if (key == "tolerance") { if(value < 0.005 || value > 0.6) throw std::invalid_argument("Invalid tolerance"); tolerance=static_cast<double>(value); return; }
        if (key == "transition") { if(value < 0.005 || value > 0.3) throw std::invalid_argument("Invalid transition"); transition=static_cast<double>(value); return; }
        if (key == "despill") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid despill"); despill=static_cast<double>(value); return; }
        if (key == "feather") { if(value < 0 || value > 12) throw std::invalid_argument("Invalid feather"); feather=static_cast<double>(value); return; }
        if (key == "edge_shift") { if(value < -8 || value > 8) throw std::invalid_argument("Invalid edge_shift"); edge_shift=static_cast<double>(value); return; }
        if (key == "refine") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid refine"); refine=static_cast<double>(value); return; }
        if (key == "blur") { if(value < 0 || value > 80) throw std::invalid_argument("Invalid blur"); blur=static_cast<double>(value); return; }
        if (key == "fill_r") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid fill_r"); fill_r=static_cast<double>(value); return; }
        if (key == "fill_g") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid fill_g"); fill_g=static_cast<double>(value); return; }
        if (key == "fill_b") { if(value < 0 || value > 1) throw std::invalid_argument("Invalid fill_b"); fill_b=static_cast<double>(value); return; }
        throw std::invalid_argument("Unknown parameter: " + key);
    }
    template<class F> void forEach(F f) const {
        f("method", double(method));
        f("output", double(output));
        f("key_r", double(key_r));
        f("key_g", double(key_g));
        f("key_b", double(key_b));
        f("tolerance", double(tolerance));
        f("transition", double(transition));
        f("despill", double(despill));
        f("feather", double(feather));
        f("edge_shift", double(edge_shift));
        f("refine", double(refine));
        f("blur", double(blur));
        f("fill_r", double(fill_r));
        f("fill_g", double(fill_g));
        f("fill_b", double(fill_b));
    }
};
}
