#!/usr/bin/env python3
"""Single source for engine/UI parameters, presets and all generated contracts.
Only Python's standard library is used, at development/build time, not playback.
"""
from pathlib import Path
import json, sys, xml.etree.ElementTree as ET
ROOT = Path(__file__).resolve().parents[1]
# name, label, minimum, maximum, default, UI decimals, group
PARAMS = [
 ("exposure", "Яркость", -2, 2, 0, 2, "light"),
 ("temperature", "Теплее / холоднее", -100, 100, 0, 0, "color"),
 ("tint", "Зелёный / пурпурный", -100, 100, 0, 0, "color"),
 ("contrast", "Контраст", -50, 50, 0, 0, "light"),
 ("shadows", "Тени", -50, 50, 0, 0, "light"),
 ("highlights", "Светлые участки", -50, 50, 0, 0, "light"),
 ("saturation", "Насыщенность", 0, 150, 100, 0, "color"),
 ("protection", "Защита светов", 0, 100, 100, 0, "light"),
 ("mix", "Сила общего стиля", 0, 100, 100, 0, "main"),
 ("auto_strength", "Сила выравнивания", 0, 100, 100, 0, "auto"),
 ("auto_ev", "Авто: экспозиция", -1, 1, 0, 4, "internal"),
 ("auto_r", "Авто: красный, EV", -0.25, 0.25, 0, 5, "internal"),
 ("auto_b", "Авто: синий, EV", -0.25, 0.25, 0, 5, "internal"),
 ("auto_contrast", "Авто: контраст", -0.12, 0.12, 0, 5, "internal"),
 ("transfer", "Передаточная функция (0: BT.709; 1: sRGB)", 0, 1, 0, 0, "internal"),
]
LOOKS = [
 ("neutral", "Естественный", "Без стилизации. Начальная точка для выравнивания.", {}),
 ("soft", "Мягкий", "Спокойный контраст, мягче светлые участки.", {"contrast":-8,"shadows":8,"highlights":-10,"saturation":96}),
 ("warm", "Тёплый", "Умеренное тепло без сильного жёлтого оттенка.", {"temperature":18,"contrast":3,"highlights":-6,"saturation":102}),
 ("sunimo", "Уют", "Тёплая мастерская; цвета изделий не нужно разгонять.", {"temperature":12,"tint":2,"contrast":5,"shadows":6,"highlights":-8,"saturation":104}),
 ("product", "Товар / детали", "Сдержанный старт для съёмки изделий, не калибровка цвета.", {"contrast":5,"highlights":-5,"saturation":100}),
 ("cool", "Прохладный", "Лёгкий холодный оттенок.", {"temperature":-14,"contrast":6,"shadows":3,"saturation":96}),
 ("muted", "Приглушённый", "Ниже насыщенность и контраст, без имитации плёнки.", {"contrast":-7,"shadows":4,"highlights":-9,"saturation":82}),
 ("mono", "Чёрно-белый", "Чистое чёрно-белое изображение, без шума и резкости.", {"contrast":10,"shadows":4,"highlights":-8,"saturation":0}),
]
PANEL_TIPS = {
 "exposure": "Общая яркость без изменения автоматического выравнивания.",
 "temperature": "Сдвиг в тёплую или холодную сторону.",
 "tint": "Сдвиг между зелёным и пурпурным.",
 "contrast": "Разница между светлыми и тёмными участками.",
 "shadows": "Осветляет или затемняет тёмные участки.",
 "highlights": "Осветляет или затемняет светлые участки.",
 "saturation": "Интенсивность цвета; 0% даёт чёрно-белое изображение.",
 "protection": "Мягко сжимает новые пересветы после коррекции.",
 "mix": "Сила общего стиля; автоматическое выравнивание сохраняется.",
 "auto_strength": "Сила рассчитанного выравнивания; ручной стиль сохраняется.",
}
def generate():
 h = ['// GENERATED by Color/scripts/generate_ui.py. DO NOT EDIT.', '#pragma once',
      '#include <array>', '#include <string_view>', '#include <cstddef>', 'namespace studio_color {',
      'struct Params {']
 for name, _, lo, hi, default, _, _ in PARAMS: h.append(f'    double {name} = {float(default)};')
 h += ['};','struct ParamSpec { const char* id; const char* label; double minimum, maximum, defaultValue; int decimals; const char* group; double Params::*field; };',
       f'inline constexpr std::array<ParamSpec, {len(PARAMS)}> paramSpecs{{{{']
 for name,label,lo,hi,default,dec,group in PARAMS:
  h.append(f'    {{"{name}", "{label}", {float(lo)}, {float(hi)}, {float(default)}, {dec}, "{group}", &Params::{name}}},')
 h += ['}};', 'struct BuiltinPreset { const char* id; const char* name; const char* description; Params params; };',
       f'inline std::array<BuiltinPreset, {len(LOOKS)}> builtinPresets() {{',f'    std::array<BuiltinPreset, {len(LOOKS)}> result{{}};']
 for i,(id,name,desc,overrides) in enumerate(LOOKS):
  h += [f'    result[{i}] = {{"{id}", "{name}", "{desc}", Params{{}}}};']
  h += [f'    result[{i}].params.{n} = {float(v)};' for n,v in overrides.items()]
 h += ['    return result;', '}', '} // namespace studio_color', '']
 root=ET.Element('effect', {'tag':'studio.color','id':'studio_color','type':'video','LC_NUMERIC':'C'})
 ET.SubElement(root,'name').text='FactMontage: Цвет'
 ET.SubElement(root,'description').text='SDR 8-бит. Единый цвет, сохранённые поправки; без анализа при воспроизведении.'
 ET.SubElement(root,'author').text='SUNIMO contributors'
 ET.SubElement(root,'version').text='1'
 for name,label,lo,hi,default,dec,group in PARAMS:
  a={'name':name,'type':'constant','default':str(default),'min':str(lo),'max':str(hi),'factor':'1','decimals':str(dec)}
  # Internal properties must persist through Kdenlive XML/model, not UI-less sidecars.
  if group in ('internal','auto'): a['type']='fixed';a['value']=str(default)
  par=ET.SubElement(root,'parameter',a);ET.SubElement(par,'name').text=label
 # Adapter-level metadata: serialized through the editor model, not exposed as user sliders.
 for name,value in (("studio_input_validated","0"),("studio_color_algorithm","sdr-primary-v1")):
  par=ET.SubElement(root,'parameter',{'name':name,'type':'fixed','default':value,'value':value})
  ET.SubElement(par,'name').text=name
 ET.indent(root,space='  ')
 schema={'schema':'studio.color/1','algorithm':'sdr-primary-v1','working_pixels':'straight RGBA8888; full RGB range; Rec.709 primaries',
  'adapter_metadata':{'studio_input_validated':0,'studio_color_algorithm':'sdr-primary-v1'},
  'parameters':[dict(zip(('id','label','min','max','default','decimals','group'), x)) for x in PARAMS],
  'presets':[{'schema':'studio.color.preset/1','id':i,'name':n,'description':d,'manual':{k:overrides.get(k,default) for k,_,_,_,default,_,group in PARAMS if group not in ('internal','auto')}} for i,n,d,overrides in LOOKS]}
 groups=[
  {'key':'main','label':'Сила','keys':['mix'],'collapsed':False},
  {'key':'light','label':'Свет','keys':['exposure','contrast','shadows','highlights','protection'],'collapsed':False},
  {'key':'color','label':'Цвет и насыщенность','keys':['temperature','tint','saturation'],'collapsed':True},
 ]
 percent={'saturation','protection','mix','auto_strength'}
 controls=[]
 for name,label,lo,hi,default,dec,group in PARAMS:
  if group in ('internal','auto'): continue
  controls.append({'key':name,'label':label,'kind':'number','lo':lo,'hi':hi,'value':default,
                   'suffix':'%' if name in percent else (' EV' if name=='exposure' else ''),
                   'decimals':min(dec,2),'tip':PANEL_TIPS[name]})
 panel={'version':2,'effect':'studio_color','service':'studio.color','groups':groups,
        'controls':controls,'presets':schema['presets']}
 y=['schema_version: 7.0','type: filter','identifier: studio.color','title: Studio Color','version: 1','creator: Studio Color contributors','license: GPLv3','language: en',
    'tags:', '  - Video', 'description: Experimental SDR 8-bit primary correction; no per-frame automatic estimation.', 'parameters:']
 for name,label,lo,hi,default,dec,group in PARAMS:
  y += [f'  - identifier: {name}',f'    title: "{label}"','    type: float',f'    minimum: {lo}',f'    maximum: {hi}',f'    default: {default}','    mutable: yes','    animation: no']
 return {'include/studio_color/params_generated.hpp':'\n'.join(h),'kdenlive/studio_color.xml':'<?xml version="1.0" encoding="UTF-8"?>\n'+ET.tostring(root,encoding='unicode')+'\n',
 'kdenlive/color_contract.json':json.dumps(schema,ensure_ascii=False,indent=2)+'\n',
 'kdenlive/studio_color.json':json.dumps(panel,ensure_ascii=False,indent=2)+'\n',
 'kdenlive/filter_studio_color.yml':'\n'.join(y)+'\n',
 **{f'presets/{x["id"]}.json':json.dumps(x,ensure_ascii=False,indent=2)+'\n' for x in schema['presets']}}
if __name__=='__main__':
 check='--check' in sys.argv
 failed=[]
 for name,text in generate().items():
  p=ROOT/name
  if check:
   if not p.is_file() or p.read_text(encoding='utf-8')!=text: failed.append(name)
  else: p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8',newline='\n')
 if failed: raise SystemExit('Out of date: '+', '.join(failed))
 print('Generated contract: OK' if check else 'Generated parameters, XML, JSON, YAML, presets')
