// GENERATED by Color/scripts/generate_ui.py. DO NOT EDIT.
#pragma once
#include <array>
#include <string_view>
#include <cstddef>
namespace studio_color {
struct Params {
    double exposure = 0.0;
    double temperature = 0.0;
    double tint = 0.0;
    double contrast = 0.0;
    double shadows = 0.0;
    double highlights = 0.0;
    double saturation = 100.0;
    double protection = 100.0;
    double mix = 100.0;
    double auto_strength = 100.0;
    double auto_ev = 0.0;
    double auto_r = 0.0;
    double auto_b = 0.0;
    double auto_contrast = 0.0;
    double transfer = 0.0;
};
struct ParamSpec { const char* id; const char* label; double minimum, maximum, defaultValue; int decimals; const char* group; double Params::*field; };
inline constexpr std::array<ParamSpec, 15> paramSpecs{{
    {"exposure", "Яркость", -2.0, 2.0, 0.0, 2, "light", &Params::exposure},
    {"temperature", "Теплее / холоднее", -100.0, 100.0, 0.0, 0, "color", &Params::temperature},
    {"tint", "Зелёный / пурпурный", -100.0, 100.0, 0.0, 0, "color", &Params::tint},
    {"contrast", "Контраст", -50.0, 50.0, 0.0, 0, "light", &Params::contrast},
    {"shadows", "Тени", -50.0, 50.0, 0.0, 0, "light", &Params::shadows},
    {"highlights", "Светлые участки", -50.0, 50.0, 0.0, 0, "light", &Params::highlights},
    {"saturation", "Насыщенность", 0.0, 150.0, 100.0, 0, "color", &Params::saturation},
    {"protection", "Защита светов", 0.0, 100.0, 100.0, 0, "light", &Params::protection},
    {"mix", "Сила общего стиля", 0.0, 100.0, 100.0, 0, "main", &Params::mix},
    {"auto_strength", "Сила выравнивания", 0.0, 100.0, 100.0, 0, "auto", &Params::auto_strength},
    {"auto_ev", "Авто: экспозиция", -1.0, 1.0, 0.0, 4, "internal", &Params::auto_ev},
    {"auto_r", "Авто: красный, EV", -0.25, 0.25, 0.0, 5, "internal", &Params::auto_r},
    {"auto_b", "Авто: синий, EV", -0.25, 0.25, 0.0, 5, "internal", &Params::auto_b},
    {"auto_contrast", "Авто: контраст", -0.12, 0.12, 0.0, 5, "internal", &Params::auto_contrast},
    {"transfer", "Передаточная функция (0: BT.709; 1: sRGB)", 0.0, 1.0, 0.0, 0, "internal", &Params::transfer},
}};
struct BuiltinPreset { const char* id; const char* name; const char* description; Params params; };
inline std::array<BuiltinPreset, 8> builtinPresets() {
    std::array<BuiltinPreset, 8> result{};
    result[0] = {"neutral", "Естественный", "Без стилизации. Начальная точка для выравнивания.", Params{}};
    result[1] = {"soft", "Мягкий", "Спокойный контраст, мягче светлые участки.", Params{}};
    result[1].params.contrast = -8.0;
    result[1].params.shadows = 8.0;
    result[1].params.highlights = -10.0;
    result[1].params.saturation = 96.0;
    result[2] = {"warm", "Тёплый", "Умеренное тепло без сильного жёлтого оттенка.", Params{}};
    result[2].params.temperature = 18.0;
    result[2].params.contrast = 3.0;
    result[2].params.highlights = -6.0;
    result[2].params.saturation = 102.0;
    result[3] = {"sunimo", "Уют", "Тёплая мастерская; цвета изделий не нужно разгонять.", Params{}};
    result[3].params.temperature = 12.0;
    result[3].params.tint = 2.0;
    result[3].params.contrast = 5.0;
    result[3].params.shadows = 6.0;
    result[3].params.highlights = -8.0;
    result[3].params.saturation = 104.0;
    result[4] = {"product", "Товар / детали", "Сдержанный старт для съёмки изделий, не калибровка цвета.", Params{}};
    result[4].params.contrast = 5.0;
    result[4].params.highlights = -5.0;
    result[4].params.saturation = 100.0;
    result[5] = {"cool", "Прохладный", "Лёгкий холодный оттенок.", Params{}};
    result[5].params.temperature = -14.0;
    result[5].params.contrast = 6.0;
    result[5].params.shadows = 3.0;
    result[5].params.saturation = 96.0;
    result[6] = {"muted", "Приглушённый", "Ниже насыщенность и контраст, без имитации плёнки.", Params{}};
    result[6].params.contrast = -7.0;
    result[6].params.shadows = 4.0;
    result[6].params.highlights = -9.0;
    result[6].params.saturation = 82.0;
    result[7] = {"mono", "Чёрно-белый", "Чистое чёрно-белое изображение, без шума и резкости.", Params{}};
    result[7].params.contrast = 10.0;
    result[7].params.shadows = 4.0;
    result[7].params.highlights = -8.0;
    result[7].params.saturation = 0.0;
    return result;
}
} // namespace studio_color
