#!/usr/bin/env python3
"""Единственный источник контракта studio.background."""
from pathlib import Path
import json
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]

# key, C++ type, default, min, max, Russian label, group
PARAMS = [
    ("method", "int", 0, 0, 1, "Способ", "hidden"),
    ("output", "int", 0, 0, 2, "Результат", "result"),
    ("key_r", "double", 0, 0, 1, "Красный", "hidden"),
    ("key_g", "double", 1, 0, 1, "Зелёный", "hidden"),
    ("key_b", "double", 0, 0, 1, "Синий", "hidden"),
    ("tolerance", "double", 0.13, 0.005, 0.6, "Убрать больше фона", "key"),
    ("transition", "double", 0.08, 0.005, 0.3, "Мягкость перехода", "key"),
    ("despill", "double", 0.65, 0, 1, "Убрать цветной отсвет", "key"),
    ("feather", "double", 1.2, 0, 12, "Смягчить край", "edge"),
    ("edge_shift", "double", 0, -8, 8, "Сузить / расширить край", "edge"),
    ("refine", "double", 0.5, 0, 1, "Уточнить край", "edge"),
    ("blur", "double", 24, 0, 80, "Размытие фона", "result"),
    ("fill_r", "double", 0.12, 0, 1, "Цвет заливки: R", "hidden"),
    ("fill_g", "double", 0.12, 0, 1, "Цвет заливки: G", "hidden"),
    ("fill_b", "double", 0.14, 0, 1, "Цвет заливки: B", "hidden"),
]

PROJECT_PROPERTIES = [
    ("mask_asset", ""),
    ("source_sha256", ""),
    ("recipe_sha256", ""),
    ("sample_offset", "0"),
    ("analysis_size", "768"),
    ("static_image", "0"),
]

BASE = {parameter[0]: parameter[2] for parameter in PARAMS}


def preset(identifier, name, description, **patch):
    return {
        "schema": "studio.background.preset/1",
        "id": identifier,
        "name": name,
        "description": description,
        "preview": f"previews/background_{identifier}",
        "animated": True,
        "values": dict(BASE, **patch),
    }


PRESETS = [
    preset("green", "Зелёный фон", "Точный ключ для ровного зелёного экрана."),
    preset("blue", "Синий фон", "Точный ключ для ровного синего экрана.", key_g=0, key_b=1),
    preset("soft_chroma", "Мягкий хромакей", "Мягче край и сильнее подавление отсвета.", transition=0.1, despill=0.8, feather=2.5),
    preset("person_blur", "Человек · размытие", "Сохраняет человека и мягко размывает фон.", method=1, output=1, despill=0),
    preset("person_alpha", "Человек · прозрачность", "Сохраняет человека на прозрачном фоне.", method=1, output=0, despill=0, feather=0.8),
    preset("person_color", "Человек · цвет", "Заменяет фон спокойным однотонным цветом.", method=1, output=2, despill=0),
]


def control(key, label, lo, hi, value, suffix="", decimals=0, **extra):
    return dict(key=key, label=label, kind="number", lo=lo, hi=hi, value=value,
                suffix=suffix, decimals=decimals, **extra)


def contract():
    return {
        "version": 2,
        "effect": "studio_background",
        "service": "studio.background",
        "pixel_format": "RGBA8888-straight-SDR",
        "groups": [
            {"key": "result", "label": "Результат", "keys": ["output", "blur"], "collapsed": False},
            {"key": "key", "label": "Однотонный фон", "keys": ["tolerance", "transition", "despill"], "collapsed": True, "method": 0},
            {"key": "edge", "label": "Край", "keys": ["feather", "edge_shift", "refine"], "collapsed": True},
        ],
        "controls": [
            {"key": "output", "label": "Что сделать с фоном", "kind": "choice", "value": 0,
             "options": [
                 {"value": 0, "name": "Убрать", "description": "Оставить прозрачность."},
                 {"value": 1, "name": "Размыть", "description": "Сохранить и размыть исходный фон."},
                 {"value": 2, "name": "Залить цветом", "description": "Заменить фон выбранным цветом."},
             ]},
            control("blur", "Сила размытия", 0, 80, 24, " px", 0, visible_when={"key": "output", "equals": 1}),
            control("tolerance", "Убрать больше фона", 0.005, 0.6, 0.13, "", 3),
            control("transition", "Мягкость перехода", 0.005, 0.3, 0.08, "", 3),
            control("despill", "Убрать цветной отсвет", 0, 1, 0.65, "", 2),
            control("feather", "Смягчить край", 0, 12, 1.2, " px", 1),
            control("edge_shift", "Сузить / расширить край", -8, 8, 0, " px", 1),
            control("refine", "Уточнить край", 0, 1, 0.5, "", 2),
        ],
        "presets": PRESETS,
        "parameters": [dict(zip(("key", "type", "default", "min", "max", "label", "group"), item)) for item in PARAMS],
        "hidden_project_properties": [key for key, _ in PROJECT_PROPERTIES],
        "method_values": ["Однотонный фон", "Человек"],
        "analysis_sizes": [512, 768, 1280],
        "runtime_only_properties": ["_sbg_mask_path"],
    }


def generated_header():
    lines = [
        "// GENERATED by Background/scripts/generate_ui.py; do not edit.",
        "#pragma once",
        "#include <cmath>",
        "#include <stdexcept>",
        "#include <string>",
        "namespace sbg {",
        "struct Params {",
    ]
    for key, cpp_type, default, *_ in PARAMS:
        lines.append(f"    {cpp_type} {key} = {default};")
    lines.append("    void validate() const {")
    for key, _, _, minimum, maximum, *_ in PARAMS:
        lines.append(f'        if (!std::isfinite(double({key})) || {key} < {minimum} || {key} > {maximum}) throw std::invalid_argument("Invalid {key}");')
    lines.extend(["    }", "    void set(const std::string& key, double value) {",
                  '        if (!std::isfinite(value)) throw std::invalid_argument("Non-finite parameter");'])
    for key, cpp_type, _, minimum, maximum, *_ in PARAMS:
        integer = " || std::floor(value) != value" if cpp_type == "int" else ""
        lines.append(f'        if (key == "{key}") {{ if(value < {minimum} || value > {maximum}{integer}) throw std::invalid_argument("Invalid {key}"); {key}=static_cast<{cpp_type}>(value); return; }}')
    lines.extend(['        throw std::invalid_argument("Unknown parameter: " + key);', "    }",
                  "    template<class F> void forEach(F f) const {"])
    for key, *_ in PARAMS:
        lines.append(f'        f("{key}", double({key}));')
    lines.extend(["    }", "};", "}"])
    return "\n".join(lines) + "\n"


def generated_xml():
    effect = ET.Element("effect", {"tag": "studio.background", "id": "studio_background", "type": "hidden"})
    ET.SubElement(effect, "name").text = "FactMontage: Фон"
    ET.SubElement(effect, "description").text = "Управляется только общей панелью Монтажной студии. SDR RGBA8888."
    ET.SubElement(effect, "author").text = "Video Studio contributors"
    for key, cpp_type, default, minimum, maximum, label, _ in PARAMS:
        attrs = {"name": key, "type": "constant", "default": str(default), "min": str(minimum),
                 "max": str(maximum), "decimals": "0" if cpp_type == "int" else "3"}
        parameter = ET.SubElement(effect, "parameter", attrs)
        ET.SubElement(parameter, "name").text = label
    for key, default in PROJECT_PROPERTIES:
        ET.SubElement(effect, "parameter", {"name": key, "type": "fixed", "value": default})
    ET.indent(effect)
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(effect, encoding="unicode") + "\n"


def produce():
    return {
        ROOT / "include/studio_background/params.hpp": generated_header(),
        ROOT / "kdenlive/studio_background.json": json.dumps(contract(), ensure_ascii=False, indent=2) + "\n",
        ROOT / "kdenlive/studio_background.xml": generated_xml(),
    }


if __name__ == "__main__":
    for path, contents in produce().items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text(encoding="utf-8") != contents:
                raise SystemExit(f"Stale generated file: {path}")
        else:
            path.write_text(contents, encoding="utf-8", newline="\n")
